PLAYERSPEED = 15
ENEMYSPEED = 5
BULLETSPEED = 30
EBULLETSPEED = 20
BORDER_SIZE = 300
ENEMY_COUNT = 10
BOSS_REQUIRMENT = 12
SHOOTING_COOLDOWN = 800

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500
BACKGROUND_COLOR = "blue"
BACKGROUND_IMAGE = "background.gif"

PLAYER_IMAGE = "player.gif"
ENEMY_IMAGE = "invader.gif"
BOSS_IMAGE = "boss.gif"
BULLET_IMAGE = "bullet.gif"
EBULLET_IMAGE = "ebullet.gif"
LASER_SOUND = "laser.wav"
EXPLOSION_SOUND = "explosion-e+b.wav"
